apiVersion: v1
kind: Service
metadata:
  name: "{{  .Values.app1.Name }}-service"
spec:
  ports:
  - port: {{ .Values.app1.port }}
  selector:
    app: "{{  .Values.app1.Name }}"

---


apiVersion: v1
kind: Service
metadata:
  name: "{{  .Values.app2.Name }}-service"
spec:
  ports:
  - port: {{ .Values.app2.port }}
  selector:
    app: "{{  .Values.app2.Name }}"
